### ISSUE TITLE
Demo Website Broken?

### ISSUE THREAD

**Issue by hozza** [danpalmer/jquery.complexify.js#26]
Hi!
Looks like your demo website it not working, the function does not exist. On FireFox Dev 37.

**Comment by jlmitch5** [comment]
Yep, I'm seeing this to

**Comment by danpalmer** [comment]
Hey, thanks for reporting this, sorry it took me a while to get to it! I believe this has now been fixed, I've tested it on Firefox (where I was able to reproduce the issue).

Let me know if you have any more problems.
