### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by x09326** [danpalmer/jquery.complexify.js#35]
Hello I'm trying to add this to cdnjs.
I need to write some information like license.
But I cannot find the license WTFPL v2.
Can you send me some information about it?

https://github.com/cdnjs/cdnjs/pull/7394

Thank you.

**Comment by danpalmer** [comment]
Hi, the full text of the licence can be found here: http://www.wtfpl.net/txt/copying/

Thanks

**Comment by x09326** [comment]
Ok, we are trying to add this lib to cdnjs.
Thank you for your help!
