### ISSUE TITLE
Trigger Complexify on button click

### ISSUE THREAD

**Issue by chcdigital** [danpalmer/jquery.complexify.js#42]
Good morning Dan,

First off, a massive thank you and congratulations on Complexify it truly is fantastic!

I have a very small query, it may be my lack of JQuery skills but I am struggling to activate Complexify on a button click.

Basically what I am trying to do is allow users to input their own password, but if they want a new more secure one to click a button to generate a new one in the same field.

If I am not mistaken Complexify is triggered on this line
` $("#generated-password").on("keypress keyup keydown", function() {`

I was wondering if it is possible to do something like this (which I know doesn't work (#gen is my button ID))
`$("#generated-password").on("keypress keyup keydown"), || $("#gen").on(click), function() {`

I tried running it on an If / else function but that seemed to create a conflict.

I am a bit lost on ideas and would massively appreciate any pointers.

Many thanks again for putting Complexify together!

**Comment by danpalmer** [comment]
I don't think you'll need to change how you use Complexify to achieve this. I would suggest something along the lines of this:

```javascript
$('#gen').on('click', function() {
    var newPassword = //... generate some password here
    $('#password-field').val(newPassword); // set the value of the field to the new password
});
```

Note that this doesn't change how Complexify will be used at all, this is entirely separate.

**Comment by chcdigital** [comment]
Thanks Dan,

So I have something very similar to create the new password:
`
            $('.gen').click(

 function(){ 
//makes a password base on variables
}
			
                // displaying the password
                $('#generated-password').val(password);`

This works perfectly with Complexify, when you enter a password it is scored. Then when you click #gen it replaces the user entered field. However it does not amend the scoring of the password unless you select the field and press a key.

Which I can understand is to be expected based on this:
` $("#generated-password").on("keypress keyup keydown", function() {`

Maybe a better way to explain, is it possible for Complexify to revalue the scoring on any change in the input field '#generated-password'? Not just keystrokes?

**Comment by danpalmer** [comment]
Ah yes, you could change the list of events `"keypress keyup keydown"` to include more events, probably `change`, that should do it. Or you could manually trigger an event on it.

**Comment by chcdigital** [comment]
Thanks Dan, Looks like we are going in the right direction.

So its almost perfect if I use it like this;
`   $("#generated-password").change("keypress keyup keydown", function() {`

But it will only trigger when you keypress enter - I guess that what counts as a change on an input field.

Is what your suggesting this? As that didnt make any difference:
`  $("#generated-password").on("keypress keyup keydown change", function() {`

I really appreciate the direction on this!

**Comment by danpalmer** [comment]
In that case I think you will need to manually trigger the change event on the password field when you update it.

**Comment by chcdigital** [comment]
Perfect! Thanks Dan!

On the off chance that someone needs to do this - here's what got this going
`$('.gen').click(

function(){
//makes a password base on variables
}

            // displaying the password
            $('#generated-password').val(password);

			$( "#generated-password" ).trigger( "click" );`

Then a small amend to Complexify

`$("#generated-password").on("input change click", function() {`

Many thanks again Dan!

**Comment by danpalmer** [comment]
No problem, glad it's working.
